kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reaper-rolebinding
subjects:
- kind: ServiceAccount
  name: pod-reaper-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pod-reaper-role
  apiGroup: rbac.authorization.k8s.io