environments:
  default:
    values:
    - environments/default.yaml.gotmpl
---
helmfiles:
- path: helmfiles/gpu-operator/helmfile.yaml
  values:
  - gpuOperator:
    {{ toYaml .Values.gpuOperator | nindent 6 }}
- path: helmfiles/prometheus-stack/helmfile.yaml
  values:
  - prometheusStack:
    {{ toYaml .Values.prometheusStack | nindent 6 }}
- path: helmfiles/nfs-server/helmfile.yaml
  values:
  - nfsServer:
    {{ toYaml .Values.nfsServer | nindent 6 }}
