repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  createNamespace: true
  wait: true

releases:
- name: prometheus-stack
  namespace: {{ .Values.prometheusStack.namespace }}
  version: 18.0.1
  chart: prometheus-community/kube-prometheus-stack
  condition: prometheusStack.enabled
  values:
  - values.yaml.gotmpl
  - {{ toYaml .Values.prometheusStack.values | nindent 4 }}
