image: "node:10.15.0"

default:
  before_script:
    - pwd
    - ls
    - node --version
    - yarn --version
    - npm --version
    - npm install -g firebase-tools
    - yarn
    - cd functions
    - npm install
    - cd ..

build_and_deploy:
  script: 
    - vue-cli-service build
    - firebase deploy
