image: "node:10.15.0"

default:
  before_script:
    - node --version
    - yarn --version
    - npm --version
    - npm install -g @vue/cli
    - npm install -g firebase-tools
    - yarn
    - cd functions
    - npm install
    - cd ..

build:
  stage: build
  script:
    - npm run build

build_and_deploy:
  stage: deploy
  script: 
    - npm run build
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token "$FIREBASE_TOKEN"
