image: node:10.15.0

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/
    - functions/node_modules/

build:
  stage: build
  script:
    - cd frontend
    - yarn --silent
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - backend/public

backend:
  stage: test
  script:
    - cd backend
    - npm install --progress=false
    - node ./bin/www

deploy_functions:
  stage: deploy
  environment: Production
  only:
    - master
  script: 
    - cd functions
    - npm install -g firebase-tools
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token "$FIREBASE_TOKEN"

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo deploy start
