image: "node:10.15.0"
  
install_dependency:
  script:
    - npm install -g firebase-tools
    - yarn
    - cd functions
    - npm install
    - cd ..

check_version:
  script: 
    - node --version
    - yarn --version
    - npm --version

build:
  script: vue-cli-service build

deploy:
  script: firebase deploy