image: node:10.15.0

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/
    - functions/node_modules/

include:
  template: Serverless.gitlab-ci.yml

build:
  extends: .serverless:build:image 

deploy_staging:
  stage: deploy
  extends: .serverless:deploy:image

deploy_prod:
  stage: deploy
  extends: .serverless:deploy:image
  environment:
    name: production
  when: manual
  only:
  - master

deploy_functions:
  stage: deploy
  environment: Production
  only:
    - master
  script: 
    - cd functions
    - npm install -g firebase-tools
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token "$FIREBASE_TOKEN"
