image: "node:10.15.0"

stages:
  - .pre
  - build
  - deploy
  
install_dependency:
  stage: .pre
  script:
    - npm install -g firebase-tools
    - yarn
    - cd functions
    - npm install
    - cd ..

check_version:
  stage: .pre
  script: 
    - node --version
    - yarn --version
    - npm --version

build:
  stage: build
  script: vue-cli-service build

deploy:
  stage: deploy
  script: firebase deploy