image: "node:10.15.0"

before_script:
  - apt-get install --no-install-recommends yarn
  - node --version
  - yarn --version
  - npm --version
  - npm install -g firebase-tools
  - yarn
  - cd functions
  - npm install
  - cd ..

build:
  script:
    - vue-cli-service build

deploy:
  script:
    - firebase deploy

stages:
  - build
  - deploy
