image: node:10.15.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - frontend/node_modules/
  - backend/node_modules/
  - functions/node_modules/

include:
  template: Serverless.gitlab-ci.yml

build:
  extends: .serverless:build:image 

deploy_staging:
  stage: deploy
  extends: .serverless:deploy:image
  environment:
    name: staging

deploy_prod:
  stage: deploy
  extends: .serverless:deploy:image
  environment:
    name: production
  when: manual
  only:
  - master

deploy_functions:
  stage: deploy
  environment:
    name: production
  when: manual
  only:
  - master
  script: 
    - cd functions
    - npm install -g firebase-tools
    - npm install
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token "$FIREBASE_TOKEN"
