apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocean-frontend
  namespace: ocean
  labels:
    app: ocean
    tier: frontend
spec:
  selector:
    matchLabels:
      app: ocean
      tier: frontend
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ocean
        tier: frontend
    spec:
      containers:
        - name: ocean
          image: docker.pkg.github.com/kairos03/ocean/ocean-front
          imagePullPolicy: Always
          env:
          - name: OCEAN_BACKEND
            value: ocean-backend-service:80
          ports:
          - containerPort: 8080
          command: ['/bin/sh', '-c', "envsubst '${OCEAN_BACKEND}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
      imagePullSecrets:
        - name: github-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ocean-frontend-service
  namespace: ocean
  labels:
    app: ocean
    tier: frontend
spec:
  selector:
    app: ocean
    tier: frontend
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 38080
