apiVersion: batch/v1
kind: Job
metadata:
  name: ocean-backend-migration-job
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: ocean-backend-migration-job
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: ocean-backend-migration-job-con
        image: {{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}
        imagePullPolicy: {{ .Values.backend.image.imagePullPolicy }}
        command: ["/bin/bash","migration.sh"]
        env:
          - name: DB_HOST
            value: {{ include "mariadb.primary.host" . }}
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mariadb
                key: mariadb-password
        volumeMounts:
          - name: config
            mountPath: "/ocean-backend/ocean/ocean/settings/components/database.py"
            subPath: "database.py"
          - name: config
            mountPath: "/ocean-backend/ocean/ocean/settings/components/kubernetes.py"
            subPath: "kubernetes.py"
        resources:
          limits:
            cpu: {{ .Values.backend.resources.limits.cpu }}
            memory: {{ .Values.backend.resources.limits.memory }}
          requests:
            cpu: {{ .Values.backend.resources.requests.cpu }}
            memory: {{ .Values.backend.resources.requests.memory }}
      imagePullSecrets:
        - name: {{ .Values.backend.image.imagePullSecret }}
      volumes:
        - name: config
          configMap:
            name: ocean-backend-configmap
            items:
            - key: "kubernetes.py"
              path: "kubernetes.py"
            - key: "database.py"
              path: "database.py"
