apiVersion: v1
data:
  kubernetes.py: |
    IS_LOCAL = False
    NAMESPACE = "{{ .Release.Namespace }}"
    STORAGE_CLASS_NAME = "{{ .Values.storage.classname }}"
    ACCESS_MODES = "{{ .Values.storage.mode }}"

  database.py: |
    import pymysql
    import os
    pymysql.install_as_MySQLdb()

    DATABASES = {
        "default": {
            'ENGINE': "django.db.backends.mysql",
            'NAME': "{{ .Values.mariadb.auth.database }}",
            'HOST': "{{ include "mariadb.primary.host" . }}",
            'USER': "{{ .Values.mariadb.auth.username }}",
            'PASSWORD': os.environ['DATABASE_PASSWORD'],
            'PORT': "{{ .Values.mariadb.primary.service.port }}"
        }
    }

  ray.py: |
    RAY_IMAGE = "{{ .Values.ray.image }}"

  images.py: |
    IMAGE_REPOS = {{ .Values.repo }}

  prometheus.py: |
    PROMETHEUS_URL = "{{ .Release.Name }}-prometheus-prometheus:9090"

kind: ConfigMap
metadata:
  name: ocean-backend-configmap
