apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ocean
  name: ocean-cli-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list"]
