storageclass:
  name: local-storage

volume:
  name: local-storage-pv
  hostpath: /dev/sdb/nfs
  size: 5Ti
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ai

nfs-server-provisioner:
  enabled: true

  persistence:
    enabled: true
    storageClass: local-storage
    size: 5Ti
