apiVersion: v1
kind: Pod
metadata:
  labels:
    control-plane: controller-manager
  name: imagepush-controller-manager
spec:
  containers:
  - args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=10
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
    imagePullPolicy: IfNotPresent
    name: kube-rbac-proxy
    ports:
    - containerPort: 8443
      name: https
      protocol: TCP
  - args:
    - --health-probe-bind-address=:8081
    - --metrics-bind-address=127.0.0.1:8080
    - --leader-elect
    command:
    - /manager
    env:
    - name: JOB_IMAGE
      value: {{ .Values.job.image.name }}:{{ .Values.job.image.tag }}
    - name: JOB_NAMESPACE
      value: {{ .Release.Namespace }}
    - name: JOB_IMAGEPULLSECRET
      value: {{ .Values.job.imagePullSecret }}
    - name: JOB_HARBORSECRET
      value: {{ .Values.job.harbor.imagePullSecret }}
    - name: JOB_SERVICEACCOUNT
      value: imagepush-controller-viewer
    - name: IN_CLUSTER
      value: "true"
    image: {{ .Values.operator.image.name }}:{{ .Values.operator.image.tag }}
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8081
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 1
    name: manager
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: 8081
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: {{ .Values.operator.resources.limits.cpu }}
        memory: {{ .Values.operator.resources.limits.memory }}
      requests:
        cpu: {{ .Values.operator.resources.requests.cpu }}
        memory: {{ .Values.operator.resources.limits.memory }}
    securityContext:
      allowPrivilegeEscalation: false
  imagePullSecrets:
  - name: {{ .Values.operator.imagePullSecret }}
  restartPolicy: Always
  securityContext:
    runAsNonRoot: true
  serviceAccountName: imagepush-controller-manager
