
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepush-operator-manager-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  - extentions
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imagepush.ocean.ai
  resources:
  - imagepushes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imagepush.ocean.ai
  resources:
  - imagepushes/finalizers
  verbs:
  - update
- apiGroups:
  - imagepush.ocean.ai
  resources:
  - imagepushes/status
  verbs:
  - get
  - patch
  - update
