repositories:
- name: harbor
  url: https://helm.goharbor.io

helmDefaults:
  createNamespace: true
  wait: true
  timeout: 600

releases:
- name: harbor
  namespace: {{ .Values.harbor.namespace }}
  version: v1.7.3
  chart: harbor/harbor
  condition: harbor.enabled
  values:
  - values.yaml.gotmpl
  - {{ toYaml .Values.harbor.values | nindent 4 }}
