apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocean-backend-deploy
spec:
  selector:
    matchLabels:
      app: ocean-backend-deploy
  replicas: {{ .Values.backend.replicas }}
  template:
    metadata:
      labels:
        app: ocean-backend-deploy
    spec:
      serviceAccountName: ocean-backend-sa
      initContainers:
        - name: ocean-backend-initcon
          image: {{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}
          command: ["/bin/bash", "-c", "--"]
          args: ["while ! mysqladmin ping -h\"$DB_HOST\" --silent; do sleep 10; done;"]
          imagePullPolicy: {{ .Values.backend.image.imagePullPolicy }}
          ports:
            - containerPort: 8000
              name: backend-port
          env:
            - name: DB_HOST
              value: {{ .Values.mariadb.host }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.secret.name }}
                  key: {{ .Values.mariadb.secret.key }}
            - name: HARBOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.harbor.secret.name }}
                  key:  {{ .Values.harbor.secret.key }}
          volumeMounts:
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/database.py"
              subPath: "database.py"
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/kubernetes.py"
              subPath: "kubernetes.py"
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/ray.py"
              subPath: "ray.py"
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/images.py"
              subPath: "images.py"
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/prometheus.py"
              subPath: "prometheus.py"
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/harbor.py"
              subPath: "harbor.py"
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/imagepush.py"
              subPath: "imagepush.py"
          resources:
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}        
      containers:
        - name: ocean-backend-con
          image: {{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}
          command: ["gunicorn"]
          args: ["--bind", "0.0.0.0:8000", "--timeout", "0", "ocean.wsgi:application"]
          imagePullPolicy: {{ .Values.backend.image.imagePullPolicy }}
          ports:
            - containerPort: 8000
              name: backend-port
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.secret.name }}
                  key: {{ .Values.mariadb.secret.key }}
            - name: HARBOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.harbor.secret.name }}
                  key:  {{ .Values.harbor.secret.key }}
          volumeMounts:
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/database.py"
              subPath: "database.py"
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/kubernetes.py"
              subPath: "kubernetes.py"
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/ray.py"
              subPath: "ray.py"
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/images.py"
              subPath: "images.py"
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/prometheus.py"
              subPath: "prometheus.py"
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/harbor.py"
              subPath: "harbor.py"
            - name: config
              mountPath: "/ocean-backend/ocean/ocean/settings/components/imagepush.py"
              subPath: "imagepush.py"
          resources:
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}
      imagePullSecrets:
        - name: {{ .Values.backend.image.imagePullSecret }}
      volumes:
        - name: config
          configMap:
            name: ocean-backend-configmap
            items:
            - key: "kubernetes.py"
              path: "kubernetes.py"
            - key: "database.py"
              path: "database.py"
            - key: "ray.py"
              path: "ray.py"
            - key: "images.py"
              path: "images.py"
            - key: "prometheus.py"
              path: "prometheus.py"
            - key: "harbor.py"
              path: "harbor.py"
            - key: "imagepush.py"
              path: "imagepush.py"

