apiVersion: v2
appVersion: v0.1.0
name: ocean
description: Ocean Helm chart for Kubernetes
version: 0.1.0

dependencies:
- name: mariadb
  version: 9.3.17
  repository: file://subcharts/mariadb
  condition: mariadb.enabled
  alias: mariadb
- name: ray
  version: 0.1.0
  repository: file://subcharts/ray
  condition: ray.enabled
  alias: ray