backend:
  replicas: 1

  image:
    name: ghcr.io/ai-ocean/ocean-backend
    tag: main
    imagePullSecret: github-regcred
    imagePullPolicy: Always

  resources:
    requests:
      cpu: 1
      memory: 1G
    limits:
      cpu: 1
      memory: 1G

  service:
    type: ClusterIP
    ports:
        nodePort: 32081

frontend:
  replicas: 1

  image:
    name: ghcr.io/ai-ocean/ocean-frontend
    tag: main
    imagePullSecret: github-regcred
    imagePullPolicy: Always

  resources:
    requests:
      cpu: 1
      memory: 1G
    limits:
      cpu: 1
      memory: 1G

  service:
    type: NodePort
    ports:
      nodePort: 32080

# ref. https://github.com/bitnami/charts/tree/master/bitnami/mariadb
mariadb:
  commonAnnotations:
    helm.sh/resource-policy: keep
  primary:
    service:
      type: ClusterIP
      port: 3306
    resources:
      requests:
        cpu: 0.5
        memory: 1G
      limits:
        cpu: 0.5
        memory: 1G
  auth:
    username: ocean
    password: ocean
    database: ocean
  persistence:
    size: 8Gi

# ref. https://github.com/ray-project/ray/tree/master/deploy/charts/ray
ray:
  image: rayproject/ray:latest
  operatorOnly: true
  namespacedOperator: true
  operatorImage: rayproject/ray:latest

storage:
  classname: nfs-client
  mode: ReadWriteMany

gpu:
  supports:
    - nvidia-rtx-1080ti
    - nvidia-rtx-2080ti
    - nvidia-rtx-3090

global:
  storageClass: nfs-client
