name: Ocean

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  k8s-test:
    runs-on: ubuntu-20.04
    steps:
      # GitHub Action reference: https://github.com/jupyterhub/action-k3s-helm
      - name: Start k8s locally
        uses: jupyterhub/action-k3s-helm@v1
        with:
          k3s-version: v1.20.0+k3s2 # releases:  https://github.com/k3s-io/k3s/tags
          helm-version: v3.4.2 # releases:  https://github.com/helm/helm/tags

      - name: Verify function of k8s, kubectl, and helm
        run: |
          echo "kubeconfig: $KUBECONFIG"
          kubectl version
          kubectl get pods --all-namespaces

          helm version
          helm list

      - uses: actions/checkout@v2

      - name: install helm
        run: |
          cd helm
          helm dep update
          helm install ocean .

