name: Intranet

on: [push, pull_request]

env:
  USERNAME: ${{ github.actor }}
  PACKAGE_ACCESS_TOKEN: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
  IMAGE_NAME: docker.pkg.github.com/mlvc-lab/intranet/intranet
  VERSION: v0.2.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: echo
      run: echo 

    - name: login docker registry
      run: docker login docker.pkg.github.com --username $USERNAME -p $PACKAGE_ACCESS_TOKEN

    - name: docker pull cache image
      run: docker pull $IMAGE_NAME:latest

    - name: docker build
      run: docker build --cache-from $IMAGE_NAME:latest . -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest

    - name: docker push latest
      run: docker push $IMAGE_NAME:latest
    
    - name: docker push version
      if: ${{ github.ref }} == 'refs/heads/develop' || ${{ github.ref }} == 'refs/heads/mater'
      run: docker push $IMAGE_NAME:$VERSION
