name: Ocean

on: [push, pull_request]

env:
  USERNAME: ${{ github.actor }}
  PACKAGE_ACCESS_TOKEN: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
  IMAGE_NAME: docker.pkg.github.com/kairos03/ocean/ocean
  DEV_VERSION: a1
  STABLE_VERSION: v0.2.2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: login docker registry
      run: docker login docker.pkg.github.com --username $USERNAME -p $PACKAGE_ACCESS_TOKEN

    - name: docker pull cache image
      run: docker pull $IMAGE_NAME:latest

    - name: docker build
      if: ${{ always() }}
      run: docker build --cache-from $IMAGE_NAME:latest . -t $IMAGE_NAME:$STABLE_VERSION -t $IMAGE_NAME:$STABLE_VERSION$DEV_VERSION -t $IMAGE_NAME:latest

    - name: docker push latest
      run: docker push $IMAGE_NAME:latest
    
    - name: docker push dev version
      if: ${{ github.ref }} == 'refs/heads/master'
      run: docker push $IMAGE_NAME:$STABLE_VERSION$DEV_VERSION

    - name: docker push stable version
      if: ${{ github.ref }} == 'refs/heads/stage'
      run: docker push $IMAGE_NAME:$STABLE_VERSION
